### ISSUE TITLE
Plugin does not work with NextJS 15

### ISSUE THREAD

**Issue by fruhnow** [sopranopillow/fluentui-nextjs-appdir-plugin#5]
When using NextJS 15 using the Plugin fails the build because of the swc runtime mismatch. Simply bumping the versions in the Cargo-Manifests doesn't do the trick this time, as compiling the plugin fails then.

According to the swc docs the correct version should be `0.98.x`

**Logs:**
```
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("[REDACTED].ts")'
│ Caused by:
│     0: failed to invoke `[REDACTED]/node_modules/.pnpm/fluentui-next-appdir-directive@0.1.7/node_modules/fluentui-next-appdir-directive/target/wasm32-wasi/release/fluentui_next_appdir_directive.wasm` as js transform pl…
│     1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See the documentation for compatibility information. If you are an author of the plugin, please update `swc_core` to the comp…
│                         
│                        Note that if you want to use the os features like filesystem, you need to use `wasi`. Wasm itself does not have concept of filesystem.
│                         
│                        https://swc.rs/docs/plugin/selecting-swc-core
│        
│                        See https://plugins.swc.rs/versions/from-plugin-runner/0.115.1 for the list of the compatible versions.
│                         
│                        Build info: 
│                            Date: 2024-10-25
│                            Timestamp: 2024-10-25T06:57:26.570146000Z
│                            
│                        Version info: 
│                            swc_plugin_runner: 0.115.1
│                            Dependencies: VERGEN_IDEMPOTENT_OUTPUT
│                        
│     2: RuntimeError: unreachable
```

Thank you for your great work!

**Comment by sopranopillow** [comment]
thanks for reporting, will look into it!

**Comment by anishkumar127** [comment]
not working in next.js 15

`106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/pages.js:3:1
Module not found: Can't resolve 'next/dist/esm/build/templates/helpers'
failed to analyse ecmascript module '[project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js [ssr] (ecmascript)'

Caused by:
- failed to parse [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js
- Transforming and/or parsing of [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js failed
- failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See the documentation for compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
- RuntimeError: out of bounds memory access

Debug info:
- Execution of <ModuleAssetContext as AssetContext>::process_resolve_result failed
- Execution of apply_module_type failed
- Execution of *EcmascriptExports::needs_facade failed
- Execution of <EcmascriptModuleAsset as EcmascriptChunkPlaceable>::get_exports failed
- Execution of analyse_ecmascript_module failed
- failed to analyse ecmascript module '[project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js [ssr] (ecmascript)'
- Execution of <EcmascriptModuleAsset as EcmascriptParsable>::failsafe_parse failed
- Execution of parse failed
- failed to parse [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js
- Transforming and/or parsing of [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/esm/build/templates/helpers.js failed
- failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See the documentation for compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.

                  Note that if you want to use the os features like filesystem, you need to use `wasi`. Wasm itself does not have concept of filesystem.

                  https://swc.rs/docs/plugin/selecting-swc-core

                  See https://plugins.swc.rs/versions/from-plugin-runner/4.0.0 for the list of the compatible versions.

                  Build info:
                      Date: 2024-11-07
                      Timestamp: 2024-11-07T09:55:40.203904400Z

                  Version info:
                      swc_plugin_runner: 4.0.0
                      Dependencies: anyhow 1.0.93,codspeed-criterion-compat 2.7.2,criterion 0.5.1,enumset 1.1.5,futures 0.3.31,once_cell 1.20.2,parking_lot 0.12.3,serde 1.0.214,serde_json 1.0.132,swc_atoms 2.0.0,swc_common 4.0.0,swc_css_ast 4.0.1,swc_css_parser 4.0.0,swc_ecma_ast 4.0.1,swc_ecma_loader 4.0.0,swc_ecma_parser 5.0.0,swc_ecma_visit 4.0.0,swc_malloc 1.0.0,swc_plugin_proxy 4.0.0,testing 4.0.0,tokio 1.41.0,tracing 0.1.40,vergen 9.0.1,virtual-fs 0.16.0,wasmer 4.3.7,wasmer-cache 4.3.7,wasmer-compiler-cranelift 4.3.7,wasmer-wasix 0.27.0

- RuntimeError: out of bounds memory access
      at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2e0e7796dd00e450 (fluentui_next_appdir_directive.wasm[195]:0x41293)
      at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h9ba16d7e99f2ea24 (fluentui_next_appdir_directive.wasm[196]:0x43055)
      at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2e0e7796dd00e450 (fluentui_next_appdir_directive.wasm[195]:0x412d6)
      at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h9ba16d7e99f2ea24 (fluentui_next_appdir_directive.wasm[196]:0x43055)
      at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2e0e7796dd00e450 (fluentui_next_appdir_directive.wasm[195]:0x412d6)
      at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h9ba16d7e99f2ea24 (fluentui_next_appdir_directive.wasm[196]:0x43055)
      at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::hf9f5382e5cfe68e1 (fluentui_next_appdir_directive.wasm[1034]:0x1415b6)       
      at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::h1117c4582490e330 (fluentui_next_appdir_directive.wasm[1035]:0x1417db)
      at __transform_plugin_process_impl (fluentui_next_appdir_directive.wasm[900]:0x130928)
      at __transform_plugin_process_impl.command_export (fluentui_next_appdir_directive.wasm[1960]:0x1ba3df)
Import map: aliased to module "next" with subpath "/dist/esm/build/templates/helpers" inside of [project]/


https://nextjs.org/docs/messages/module-not-found


 GET / 500 in 5288ms
`

**Comment by lemichael** [comment]
First of all, thank you for this useful plugin!

I've tried to upgrade Next to 15.0.3 and got the same error. Seems like 15.0.3 requires `swc_core >= 4.0.0` (https://plugins.swc.rs/versions/range/19). For Next [15.0.0, 15.0.2], it's [0.106.0, 3.0.2] (https://plugins.swc.rs/versions/range/95).

There's my commit if you want to give it a go with Next 15.0.3:
https://github.com/sopranopillow/fluentui-nextjs-appdir-plugin/compare/master...lemichael:fluentui-nextjs-appdir-plugin:master

I can consider opening a PR but I'm not sure how to cope with compatibility between Next versions.

**Comment by sopranopillow** [comment]
no worries, I'll add this change and push it as a new minor

**Comment by sopranopillow** [comment]
Hey! `0.2.0` has been released and should be working! Tested it with latest NextJS and latest Fluent UI.

https://github.com/sopranopillow/fluentui-nextjs-appdir-plugin/commit/9e359a2f99ad05df42548cd1ea6e6be672a9237c
